In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6
                  ]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99


In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60],[65,70,75]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[2][1]

40

In [36]:
arr_2d[2][2]

45

In [37]:
arr_2d[1][1]

25

In [39]:
arr_2d[1][0]

20

In [40]:
arr_2d[2,1]

40

In [41]:
arr_2d[1,0]

20

In [42]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60],
       [65, 70, 75]])

In [54]:
arr_2d[1:4,:]

array([[20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [56]:
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
bool_arr =arr > 5

In [62]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [63]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr<3]

array([0, 1, 2])

In [65]:
arr_2d = np.arange(50).reshape(5,10)

In [66]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [71]:
arr_2d[2:,6:]

array([[26, 27, 28, 29],
       [36, 37, 38, 39],
       [46, 47, 48, 49]])

In [72]:
arr_2d[2:,1:4]

array([[21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])